package net.dataninja.ee.textEngine.facet;

import net.dataninja.ee.util.Trace;

/*
net.dataninja copyright statement
 */

/**
 * This class contains a mapping, from documents to one or more term values
 * in each document. The mapping can be static (read from an index) or
 * dynamic (generated by code).
 *
 * @author Rick Li
 */
public abstract class GroupData 
{
  /**
   * Return the ID of the first link for the given document, or -1 if there
   * are no links for that document.
   *
   * @param docId document to look for
   * @return      the first link ID, or -1 if none
   */
  public abstract int firstLink(int docId);

  /** Return the ID of the link after the specified one, or -1 if no more */
  public abstract int nextLink(int linkId);

  /** Returns the group number of the specified link */
  public abstract int linkGroup(int linkId);

  /** Get the name of the grouping field */
  public abstract String field();

  /** Get the total number of groups */
  public abstract int nGroups();

  /** Get the name of a group given its number */
  public abstract String name(int groupId);

  /** Get the parent of the given group, or -1 if group is the root */
  public abstract int parent(int groupId);

  /** Get the number of children a group has */
  public abstract int nChildren(int groupId);

  /** Get the first child of the given group, or -1 if it has no children */
  public abstract int child(int groupId);

  /** Get the sibling of the given group, or -1 if no more */
  public abstract int sibling(int groupId);

  /** Locate a group by name and return its index, or -1 if not found */
  public abstract int findGroup(String name);

  /** Compare two groups for sort order */
  public abstract int compare(int group1, int group2);

  /** Output the groups to the info trace stream */
  public void debugGroups(int parent) 
  {
    Trace.info(name(parent));
    Trace.tab();
    for (int kid = child(parent); kid >= 0; kid = sibling(kid)) {
      assert parent(kid) == parent;
      debugGroups(kid);
    }
    Trace.untab();
  }

  /** Whether the data is dynamic and thus has counts and scores available */
  public boolean isDynamic() {
    return false;
  }

  /** Only called for dynamic data: get score of a group */
  public float score(int groupId) {
    throw new UnsupportedOperationException();
  }

  /** Only called for dynamic data: get count of docs in a group */
  public int nDocHits(int groupId) {
    throw new UnsupportedOperationException();
  }
} // GroupData
